spring.application.name=rag

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.chat.client.enabled=true

spring.elasticsearch.uris=${ES_SERVER_URL}
spring.elasticsearch.username=${ES_USERNAME}
spring.elasticsearch.password=${ES_PASSWORD}
spring.ai.vectorstore.elasticsearch.dimensions=3072
spring.ai.vectorstore.elasticsearch.index-name=spring-ai-gemini-embeddings
spring.ai.vectorstore.elasticsearch.initialize-schema=true

